### ISSUE TITLE
[Suggestion] Acidic radrock spouting recipe

### ISSUE THREAD

**Issue by MarioSMB** [FrozenHydrant/create-oppenheimered#2]
Acidic radrock usually takes 4 radrock and a bucket of acid in a crafting table.  
It would be a lot more convenient to be able to spout 250mb of acid onto radrock to get acidic radrock!

**Comment by FrozenHydrant** [comment]
Good idea

**Comment by FrozenHydrant** [comment]
Should be added in latest commit
