### ISSUE TITLE
Version at front of filename

### ISSUE THREAD

**Issue by MarioSMB** [FrozenHydrant/create-oppenheimered#3]
The mod's .jar file is named 1.20.1-create_oppenheimered-1.0.0.jar, this makes it harder to find alphabetically.  
I would like to suggest naming it create_oppenheimered-1.20.1-1.0.0.jar instead, thanks.

**Comment by FrozenHydrant** [comment]
Need to remember to do this for future releases

**Comment by FrozenHydrant** [comment]
Also fixed in latest release

**Comment by MarioSMB** [comment]
Very nice, thank you!
