### ISSUE TITLE
Galena Iron Ore does not have a Crushing Wheel recipe

### ISSUE THREAD

**Issue by MFNmodding** [FrozenHydrant/create-oppenheimered#6]
The title sums it up pretty well. I've noticed that other Alexs Caves ores have crushing wheel recipes, but galena iron ore does not.
I found out when I put several stacks into my crushing wheel and got nothing back except what hadn't been crushed yet.
(Fun Fact! If something doesn't have a crushing wheel recipe and you put it in anyways, the crushing wheels just delete the item!)

**Comment by FrozenHydrant** [comment]
Apologies for late reply, this should be fixed with latest version
